version: "3.8"

services:
  web:
    build: ../../backend/
    volumes:
      - ../../backend:/app/
    environment:
      DJANGO_ADMIN_USERNAME: asiamarket676@mail.ru
      DJANGO_ADMIN_PASSWORD: 82738899
  nginx:
    build: ./nginx
    volumes:
      - ../../backend/staticfiles:/app/static
      - ../../httpdocs:/app/http
    ports:
      - "8920:80"
    depends_on:
      - web
