version: "3.8"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app/
  nginx:
    build: ./production/nginx
    volumes:
      - ./staticfiles:/app/static
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
