# Generated by Django 3.1.6 on 2021-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='iin',
            field=models.CharField(max_length=255, verbose_name='ИИН'),
        ),
    ]
